version: '3.8'

networks:
  default:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./srcs/nginx/.
    ports:
      - "80:80"
    volumes:
      - web:/var/www/html
    networks:
      default:

  wordpress:
    container_name: wp-php
    build: ./srcs/wordpress/.
    volumes:
      - web:/var/www/html
    networks:
      default:
    env_file:
      - .env
  
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb/.
    volumes:
      - web:/var/www/html
    networks:
      default:

volumes:
  web:
    driver: local
    driver_opts:
      device: $HOME/web
      type: none
      o: bind
  db:
    driver: local
    driver_opts:
      device: $HOME/web
      type: none
      o: bind
