version: '3.8'

services:
  nginx:
    container_name: nginx
    build: ./srcs/nginx/.
    ports:
      - "80:80"
    volumes:
      - $HOME/web:/var/www/html
    networks:
      inception:

  wordpress:
    container_name: wp-php
    build: ./srcs/wordpress/.
    volumes:
      - $HOME/web:/var/www/html
    networks:
      inception:
    env_file:
      - .env
  
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb/.
    volumes:
      - $HOME/web:/var/www/html
    networks:
      inception:
networks:
  inception:
