version: '3.3'

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    networks:
      inception:

  wordpress:
    container_name: wp-php
    build: ./wordpress/.
    volumes:
      - web:/var/www/html
    networks:
      inception:
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./mariadb/.
    volumes:
      - db:/var/www/mysql
    networks:
      inception:


volumes:
  web:
    driver: local
    driver_opts:
      device: $HOME/data/web
      type: none
      o: bind
  db:
    driver: local
    driver_opts:
      device: $HOME/data/db
      type: none
      o: bind

networks:
  inception:
    driver: bridge
